version: '3.7'

services:

  backend:
    build:
      context: ./spring-boot-docker
      dockerfile: Dockerfile
    ports:
      - '8000:8080'

  front-end:
    container_name: front-end
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
